### ISSUE TITLE
How do we check whether a commit message contains a given string which is not on first line

### ISSUE THREAD

**Issue by RobinMaub** [Pike/pygrep#1]
Hi everyone,

I would know how to check if my commit message contains the Gitlab changelog tag (Changelog:).

Commit message are used to be:
```
Commit message

Changelog: other
```
I wrote the following:
```
repo: local
hooks:
id: changelog-check
name: Check for changelog entry presence
language: python
entry: '(?!Changelog:)'
args: [--multiline]
stages: [commit-msg]
```
But this never raises a fail when missing or a passed when fine, it is always failing.
Thanks for your help

**Comment by Pike** [comment]
How is this related to pygrep?

**Comment by RobinMaub** [comment]
Pygrep is the way pre-commit finds string in the commit-message. Sorry if I am not at the right place to ask my question.
